version: '3.8'

services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:15
    container_name: zabbix_monitor_db
    environment:
      POSTGRES_DB: zabbix_monitor
      POSTGRES_USER: zabbix_user
      POSTGRES_PASSWORD: zabbix_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - zabbix_monitor_network
    restart: unless-stopped

  # Redis para caching
  redis:
    image: redis:7-alpine
    container_name: zabbix_monitor_redis
    ports:
      - "6379:6379"
    networks:
      - zabbix_monitor_network
    restart: unless-stopped

  # Backend FastAPI
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: zabbix_monitor_backend
    environment:
      - DATABASE_URL=postgresql://zabbix_user:zabbix_password@postgres:5432/zabbix_monitor
      - REDIS_URL=redis://redis:6379/0
      - ZABBIX_URL=${ZABBIX_URL}
      - ZABBIX_USER=${ZABBIX_USER}
      - ZABBIX_PASSWORD=${ZABBIX_PASSWORD}
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
      - DEBUG=False
      - ENVIRONMENT=production
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    networks:
      - zabbix_monitor_network
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

  # Frontend React
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: zabbix_monitor_frontend
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - zabbix_monitor_network
    restart: unless-stopped

  # Nginx reverse proxy (opcional)
  nginx:
    image: nginx:alpine
    container_name: zabbix_monitor_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - backend
      - frontend
    networks:
      - zabbix_monitor_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  zabbix_monitor_network:
    driver: bridge 